services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DB_CONNECTION_STRING=mysql+aiomysql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network
  
  test:
    build: .
    volumes:
      - .:/app
    command: ["pytest", "-s"]
    profiles:
      - test  
  db:
    image: mariadb:10.6.17-focal
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - assistant_db-data:/var/lib/mysql
    networks:
      - app-network

  vector-db:
    image: qdrant/qdrant:latest-unprivileged
    ports:
      - "6333:6333"
    environment:
      - VECTOR_DB_PASSWORD=${VECTOR_DB_PASSWORD}
    networks:
      - app-network

volumes:
  assistant_db-data:

networks:
  app-network:
    driver: bridge
